import { GoogleGenAI } from '@google/genai';
import { getAuthUser } from '../jwt-auth.js';
import { storage } from '../storage.js';

// Initialize Google GenAI client
const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_API_KEY
});

export default async function handler(req, res) {
    // Only allow POST requests
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        // Check authentication
        const user = getAuthUser(req);
        if (!user) {
            return res.status(401).json({ error: 'Not authenticated' });
        }

        // Refresh user data to get latest credits
        const users = await storage.getUsers();
        const fullUser = users.find(u => u.id === user.id);
        if (!fullUser) {
            return res.status(401).json({ error: 'User not found' });
        }

        // Check if user has enough credits (video generation costs more - let's say 3 credits)
        const VIDEO_GENERATION_COST = 3;
        if (!fullUser.credits || fullUser.credits < VIDEO_GENERATION_COST) {
            return res.status(403).json({ 
                error: `Insufficient credits. Video generation requires ${VIDEO_GENERATION_COST} credits. You have ${fullUser.credits || 0}.` 
            });
        }

        const { prompt, duration, aspectRatio, frames } = req.body;

        if (!prompt) {
            return res.status(400).json({ error: 'No prompt provided' });
        }

        console.log('Generating video with Veo 3.1:', {
            prompt,
            duration: duration || 8,
            aspectRatio: aspectRatio || '16:9',
            frameCount: frames ? Object.keys(frames).filter(k => frames[k]).length : 0
        });

        // Build the request for Veo 3.1
        const requestConfig = {
            model: 'veo-3.1',
            prompt: prompt,
            config: {
                duration: duration || 8, // Default 8 seconds
                aspectRatio: aspectRatio || '16:9'
            }
        };

        // Add frame guidance if provided
        if (frames) {
            const frameGuidance = {};
            
            // Process first frame
            if (frames.first) {
                let imageData = frames.first;
                if (imageData.includes('base64,')) {
                    imageData = imageData.split('base64,')[1];
                }
                frameGuidance.firstFrame = {
                    image: {
                        imageBytes: imageData
                    }
                };
            }
            
            // Process middle frame
            if (frames.middle) {
                let imageData = frames.middle;
                if (imageData.includes('base64,')) {
                    imageData = imageData.split('base64,')[1];
                }
                frameGuidance.middleFrame = {
                    image: {
                        imageBytes: imageData
                    }
                };
            }
            
            // Process last frame
            if (frames.last) {
                let imageData = frames.last;
                if (imageData.includes('base64,')) {
                    imageData = imageData.split('base64,')[1];
                }
                frameGuidance.lastFrame = {
                    image: {
                        imageBytes: imageData
                    }
                };
            }
            
            // Only add frameGuidance if at least one frame is provided
            if (Object.keys(frameGuidance).length > 0) {
                requestConfig.config.frameGuidance = frameGuidance;
            }
        }

        // Generate video using Veo 3.1
        console.log('Calling Veo 3.1 API...');
        const response = await ai.models.generateVideo(requestConfig);

        // Process response
        if (!response || !response.generatedVideo) {
            console.error('No video generated:', JSON.stringify(response, null, 2));
            return res.status(500).json({ 
                error: 'No video generated by the model.'
            });
        }

        // Get the video URL or bytes
        const videoData = response.generatedVideo;
        
        // Deduct credits from user
        const userIndex = users.findIndex(u => u.id === fullUser.id);
        if (userIndex !== -1) {
            users[userIndex].credits = (users[userIndex].credits || 0) - VIDEO_GENERATION_COST;
            await storage.setUsers(users);
        }

        // Return video data
        res.json({
            video: videoData.videoUrl || videoData.videoBytes,
            creditsRemaining: users[userIndex].credits,
            duration: duration || 8,
            aspectRatio: aspectRatio || '16:9'
        });

    } catch (error) {
        console.error('Error generating video:', error);
        res.status(500).json({ 
            error: error.message || 'Failed to generate video'
        });
    }
}
