import { GoogleGenAI } from '@google/genai';
import { getAuthUser } from '../jwt-auth.js';
import { storage } from '../storage.js';

// Initialize Google GenAI client
const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_API_KEY
});

export default async function handler(req, res) {
    // Only allow POST requests
    if (req.method !== 'POST') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        // Check authentication
        const user = getAuthUser(req);
        if (!user) {
            return res.status(401).json({ error: 'Not authenticated' });
        }

        // Refresh user data from storage to get latest credits
        const users = await storage.getUsers();
        const fullUser = users.find(u => u.id === user.id);
        
        if (!fullUser) {
            return res.status(401).json({ error: 'User not found' });
        }

        // Check if user has enough credits
        if (!fullUser.credits || fullUser.credits < 1) {
            return res.status(403).json({ error: 'Insufficient credits. Please contact an administrator.' });
        }

        const { prompt, images, aspectRatio } = req.body;

        if (!prompt) {
            return res.status(400).json({ error: 'No prompt provided' });
        }

        console.log('Generating image with prompt:', prompt);
        console.log('Number of input images:', images ? images.length : 0);

        let result = {
            text: null,
            image: null
        };

        // Choose generation method based on whether input images are provided
        if (images && images.length > 0) {
            // IMAGE-TO-IMAGE: Use Gemini 2.5 Flash
            console.log('Using Gemini 2.5 Flash for image-to-image generation');
            
            let contents = [];
            contents.push({ text: `Based on these ${images.length} input image${images.length > 1 ? 's' : ''}, ${prompt}` });
            
            // Add all images to the contents
            images.forEach((image) => {
                let imageData = image;
                if (imageData.includes('base64,')) {
                    imageData = imageData.split('base64,')[1];
                }
                
                contents.push({
                    inlineData: {
                        mimeType: 'image/png',
                        data: imageData
                    }
                });
            });

            const response = await ai.models.generateContent({
                model: 'gemini-2.5-flash-image',
                contents: contents
            });

            if (!response || !response.candidates || !response.candidates[0]) {
                return res.status(500).json({ error: 'Unexpected response from AI model.' });
            }

            const candidate = response.candidates[0];
            
            if (!candidate.content || !candidate.content.parts) {
                return res.status(500).json({ error: 'No content returned from AI model.' });
            }

            for (const part of candidate.content.parts) {
                if (part.text) {
                    result.text = part.text;
                } else if (part.inlineData) {
                    const imageData = part.inlineData.data;
                    result.image = `data:image/png;base64,${imageData}`;
                }
            }

        } else {
            // TEXT-TO-IMAGE: Use Imagen 4.0
            console.log('Using Imagen 4.0 for text-to-image generation');
            
            const SUPPORTED_ASPECT_RATIOS = new Set(['1:1', '16:9', '9:16', '4:3', '3:4']);
            const validAspectRatio = SUPPORTED_ASPECT_RATIOS.has(aspectRatio) ? aspectRatio : '1:1';

            const response = await ai.models.generateImages({
                model: 'imagen-4.0-generate-001',
                prompt: prompt,
                config: {
                    numberOfImages: 1,
                    aspectRatio: validAspectRatio
                }
            });

            if (!response || !response.generatedImages || response.generatedImages.length === 0) {
                return res.status(500).json({ error: 'No images generated by the model.' });
            }

            const generatedImage = response.generatedImages[0];
            const imageBytes = generatedImage.image.imageBytes;
            result.image = `data:image/png;base64,${imageBytes}`;
        }

        // Deduct one credit and increment used credits
        const userIndex = users.findIndex(u => u.id === fullUser.id);
        
        if (userIndex !== -1) {
            users[userIndex].credits = (users[userIndex].credits || 0) - 1;
            users[userIndex].usedCredits = (users[userIndex].usedCredits || 0) + 1;
            await storage.setUsers(users);
            
            result.creditsRemaining = users[userIndex].credits;
        }

        res.json(result);
    } catch (error) {
        console.error('Error generating content:', error);
        res.status(500).json({ 
            error: error.message || 'Failed to generate content'
        });
    }
}
